### ISSUE TITLE
Offical site is not working

### ISSUE THREAD

**Issue by TM-Yang** [avosskuehler/ogama#4]
I try to connect the offical web : www.ogama.net

But can't open 

The error message is : Recoverable fatal error: ini_set(): Cannot set 'user' save handler by ini_set() or session_module_name() in /homepages/35/d319477412/htdocs/Ogama/sites/default/settings.php on line 144

I want to resolve this problems

**Comment by denaefordrobin** [comment]
I'm having the same issue.  @avosskuehler can you help us out here?

**Comment by avosskuehler** [comment]
Thanks for your report, sorry for the offline time. My provider moved to another php version which didn´t work together with the outdated drupal version i used for the website.
I updated the site, so that it´s accessible again.

**Comment by avosskuehler** [comment]
Closed
