### ISSUE TITLE
Error using webcam for recording

### ISSUE THREAD

**Issue by dkreu** [avosskuehler/ogama#5]
Hello,

using my webcam for recording, I received the following error. Could you please give me some advice how to solve the issue?
"Could not start recording, because we received no gaze samples from the tracking device during 5 seconds."

Many thanks in advance!

**Comment by avosskuehler** [comment]
Using a normal webcam for recording is not applicable for eye tracking, its just not able to detect relative eye movements in an adequate manner. You need do have an infrared prepared device. If you have tried to use the gazetracker or haytham tracker they could not detect the IR reflex needed to calculate the fixations, so no gaze samples were received as the message states. Have a look at the haytham site for some more information... http://www.dmardanbegi.com/haytham/get_started.html
