### ISSUE TITLE
Using Ogama algorithms outside of Winform application

### ISSUE THREAD

**Issue by cipristupi** [avosskuehler/ogama#6]
Hi, 
It is possible to use all the algorithms implemented in Ogama outside of Winform application. 
I want to use the algorithms from Ogama behind an web api/service. The application will get the data from eye tracking application and display it into a webpage. 

Thank you,
Ciprian

**Comment by avosskuehler** [comment]
Maybe a bit late, but yes you are free to use all of the algorithms as long as you respect the license. The only exception is the fixation detection algorithm from LC Technologies which has its own license.
