### ISSUE TITLE
Connection to Tobii eye tracker fails after the first time connecting

### ISSUE THREAD

**Issue by hammad-a** [avosskuehler/ogama#7]
I am trying to use OGAMA with a Tobii Pro X3-120 (with an external processing unit) eye tracker, and I have been seeing a "Connection failed" error whenever I try to record a new trial (screenshot attached). The Tobii Pro Eye Tracker Manager, and other similar applications, still recognize the tracker so I think the issue really is just with OGAMA.

The connection works fine the first time I try to connect the tracker (e.g., creating a new Windows 10 account, using OGAMA on it for the first time). It shows me available trackers and Tobii is listed as available. Once I connect initially, a Tobii tab appears in the left side pane of the application. If I close OGAMA then and try to open again, it will fail to connect with the error message (see screenshot). Do you have any suggestions here? The only workaround I have been able to find so far is to either keep the tracker connected with OGAMA running all the time, or create a new Windows user account every time I close OGAMA and want to record a new experiment trial.

I am using Windows 10 with OGAMA 5.1, if that is relevant. 

![Screen Shot 2021-09-03 at 1 48 30 PM](https://user-images.githubusercontent.com/19213418/132046929-c07c79e3-dd13-4b07-a0a3-6eeedfcb536c.png)

**Comment by avosskuehler** [comment]
I was astonished, that ogama got a succesful connection with the x3, cause tobii stated, that the original sdk which ogama uses is not valid for the x3. The workaround with the new user account may indicate, that on first start of the sdk connection a file is created that denies further connections, but this is just an idea. Cause I don´t have a x3 device at hand i can not track down the bug, but you will have to: debug and run ogama from within visual studio to get the point for the "object reference not set" error in code, to fix it. My default answer would have been: The X3 is not supported by the current version of ogama. The most recent answer would be: I think you have to implement the recent Tobii Pro SDK C for Windows 1.9 into ogama to get it to work, which is possible, but needs some time.
