### ISSUE TITLE
Old browser on the latest Ogama

### ISSUE THREAD

**Issue by srigi** [avosskuehler/ogama#8]
Hello,

I'm using Ogama v5.1 on Windows 10 20H2. Some of the websites are not displaying correctly. I checked the used browser core of Ogama and it says that the used browser is Internet Explorer 11.

Is it possible to change the used browser to something more modern?

**Comment by avosskuehler** [comment]
This is possible, but needs a huge refactoring of some of the core features, so lots of work... sorry that I have no time for that. Ogama is quite outdated in the meantime ...
