### ISSUE TITLE
Aurora recording data problem 

### ISSUE THREAD

**Issue by koraykoca** [avosskuehler/ogama#9]
Hi, 

I know you are not active for this project but I want to ask a question. I am trying to get raw/unfiltered data from Aurora eye tracker. I tried to use OGAMA and I have connection issues. My settings are the followings:

![Screenshot_1](https://user-images.githubusercontent.com/20690194/156772500-e4b7bdc7-c633-4e1b-833e-298b94551fef.png)
![Screenshot_2](https://user-images.githubusercontent.com/20690194/156772516-c20cb828-b759-4799-abf5-14ca0ab8d381.png)

When I try to connect eye tracker, I am getting the following errors: 

![Screenshot_3](https://user-images.githubusercontent.com/20690194/156773069-1a34f2d5-f390-4ddf-ad39-ec4b2a7a746f.png)
![Screenshot_4](https://user-images.githubusercontent.com/20690194/156773083-ee3cca0d-f924-422d-9202-969033c9a3cf.png)

What is the problem here? I tried also different port numbers (and the default one in the code: 8100), however couldn't solve this issue. 
How can I get sensor data or do you suggest me another method to get raw sensor data. I looked for PyGaze but it doesn't support Aurora. (I can get data using iMotions software, but I don't know which kind of filtering is going on there, that's why I am looking for open source alternatives.) Thank you.

**Comment by avosskuehler** [comment]
Hi Koray, ich habe mit dem Aurorasystem keine Erfahrung, aber es könnte einer der folgenden Fehler sein:
- Firewall blockiert IP oder Port
- 127.0.0.1 ist ja localhost also der eigene Rechner, hat der Tracker keine eigene IP?
- Der Tracker ist ja per USB verbunden, muss der Ogamarechner nicht auch 127.0.0.1 (also localhost) haben?
- Gibt es keine mitgelieferte Software, aus der man eine funktionierende connection auslesen kann?
Viele Grüße,
Adrian

**Comment by avosskuehler** [comment]
Closed due to missing answer.
